name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install mdbook
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook
          version: 0.4.52

      - name: install wavedrom
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-wavedrom
          version: 0.10.0

      - name: build book
        run: |
          cd book
          mdbook build

      - name: setup pages
        uses: actions/configure-pages@v4

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'book/book'

      - name: deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
